# Default value.
field.value.user_confirm_field:
  type: mapping
  label: Default value
  mapping:
    confirm:
      type: integer
      label: user
    value_2:
      type: boolean
      label: confirm
# Field widget.
field.widget.settings.user_confirm_field:
  type: mapping
  label: Example widget settings
  mapping:
    foo:
      type: string
      label: Foo
